apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ramann123/user-service:latest  # Replace with your Docker Hub image path
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo:27017/userdb
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer  # Exposes the service externally
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: user-service
